### ISSUE TITLE
The movingAverage function operates on samples, not minutes.

### ISSUE THREAD

**Issue by otac0n** [Graphite-Tattle/Tattle#34] opened 2012-12-16 05:30 UTC
The graphite documentation specifies that the movingAverage function operates on samples, not minutes.  However, on a 24-hour graph, Graphite condenses samples into 1-minute buckets, leading to the confusion.

For me, this means that, if I choose "3", Graphite averages the last 30 seconds (since my samples are kept at the default resolution of 10 seconds).

This is confusing, since the UI mentions "minutes", which is only true for the 24-hour graph; whereas the actual polling of the data operates on a much smaller timescale and performs the moving average on a sample-by-sample basis.

See:
http://graphite.readthedocs.org/en/1.0/functions.html

**Comment by g76r** [comment] 2016-02-16 14:08
I think the issue is solved by #52 that I've just merged into master

**Closed by g76r** 2016-02-16 14:08 UTC
Labels: processor.php and movingAverage enhancements
